name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "purvishdh@users.noreply.github.com"
          git config --global user.name "purvishdh"
          git remote add hf https://Purvish347:$HF_TOKEN@huggingface.co/spaces/Purvish347/Stock.finder
          git push hf main --force
